# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - proto use && devcontainer build --workspace-folder . .devcontainer/devcontainer.json
    silent: true
